#!/bin/bash

#SBATCH --partition=2080ti                  
#SBATCH --nodelist=aisurrey[05,07-10]        
#SBATCH --job-name=test_identity          
#SBATCH --nodes=1                          
#SBATCH --ntasks=3                         
#SBATCH --gpus-per-node=3                  
#SBATCH --cpus-per-task=8                  
#SBATCH --time=06:00:00                    
#SBATCH --mem=64G                          
#SBATCH --output=output.log               
#SBATCH --error=error.log  